version: 2
updates:
  - package-ecosystem: "python"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "numpy"
        versions: ["1.24.4"]
      - dependency-name: "scikit-learn"
        versions: ["0.24.1"]
      - dependency-name: "scikit-image"
        versions: ["0.18.1"]
      - dependency-name: "matplotlib"
        versions: ["3.7.5"]
    commit-message:
      prefix: "chore(deps): update"
    commit-args: ["-S"]
