language: python
python:
  - "3.8"
# command to install dependencies
install:
  - source scripts/get_example_data.sh
  - pip install codecov
  - python setup.py install
script:
  - python setup.py test
after_success:
  - codecov -t $CODECOV_TOKEN