
piv:
  min_window_size: null
  overlap_ratio: 0.5 
  coarse_factor: 0 
  dt: 1
  validation_method: mean_velocity
  trust_1st_iter: 0 
  validation_iter: 3 
  tolerance: 1.5 
  nb_iter_max: 1 
  sig2noise_method: peak2peak
  
tfm: 
  E: 100
  s: 0.5
  meshsize: 10
  pix_per_mu: 1.3
      
    