name: Python package workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: myenv

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install locally
      run: |
        pip install -e .
        
    - name: Install Conda dependencies
      run: conda install -c conda-forge shapely flake8 pytest-cov --yes

    - name: Test with pytest
      run: pytest --cov=. --cov-report=xml --ignore=pytraction/net/*

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: coverage.xml
